remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Dynamic Diaphragm Tracking
description: Tracking the diaphragm from 4D ultrasound during breathing (in collaboration with the University of Salford)
